data/combine_en.py
Ana sayfadaki butonların başlığının dil değiştirme kısmında tamamının ingilizce olması için metin düzeltmeleri yapıldı
=> Dil Ayarları

fe/src/App.tsx
Dil ayarlarına bağlı olarak ana sayfa ve gri butonlarının isimlendirmesi düzeltildi
=> Butonların İsimlendirmesi

fe/src/App.tsx
Dil ayarlarında butonlarda tam tersi isimler çıkıyordu. İngilizce iken türkçe, türkçe iken ingilizce çıkıyordu. Bu sorun giderildi
=> Dil Ayarları Commit

fe/src/components/data/BankData.tsx
Refactor the bank item component to have clipboard rows in a separate component and also make the overflowing words to break so that they could be rendered better on mobile devices
=> Refactor bank data and make the link wrapped in small windows

fe/package-lock.json, fe/package.json, fe/src/App.tsx, fe/src/components/Question.tsx, fe/src/components/data/CityAccommodation.tsx, fe/src/components/data/GatheringData.tsx, fe/src/components/data/HelpItemData.tsx, fe/src/components/data/PhoneData.tsx, fe/src/hooks.ts, fe/src/i18n.ts, fe/src/index.tsx, fe/src/utils/LocalStorage.ts, fe/src/utils/locales/en/translation.json, fe/src/utils/locales/tr/translation.json, fe/src/utils/types.ts, fe/src/utils/util.ts
This pr adds multiple language support that is flexible for more languages. It also stores last selected language on local storage to use for next sessions
- Add missing translations for the below sub-pages
=> Add multi lang support

fe/src/utils/locales/en/translation.json, fe/src/utils/locales/tr/translation.json
Kalacak yerler kısmında telefon numarası ile ilgili olarak ayarlanan ingilizce ve türkçe metinlerde metinlerin ikinci bölümü numaraya bitişikti görünümün düzelmesi için gerekli işlemler gerçekleştirildi
=> Metin Düzeltmesi

fe/src/components/data/BloodDonationData.tsx
Kızılay kan bağış noktaları hızlı erişimi için konum bağlantısı eklendi.
=> Kızılay Kan Bağış Noktaları Hızlı Konum Erişim

fe/src/components/Question.tsx, fe/src/components/data/UsefulLinksdata.tsx
- This pr adds support for external data
=> Add support for external links

data/parsers/karayollari_kapali_yollar.py, requirements.txt
Implementation of parser for https://www.kgm.gov.tr/Sayfalar/KGM/SiteTr/YolDanisma/TrafigeKapaliYollar.aspx
=> Feat: Karayolları kapalı yollar parser

fe/src/components/Data.tsx, fe/src/components/Question.tsx, fe/src/utils/category.ts, fe/src/utils/locales/ar/translation.json, fe/src/utils/locales/en/translation.json, fe/src/utils/locales/ku/translation.json, fe/src/utils/locales/tr/translation.json, fe/src/utils/util.ts, fe/src/variables/TreeNode.ts
=> Group main menu buttons by categories

fe/src/components/data/ArticleData.tsx, fe/src/utils/locales/ar/translation.json, fe/src/utils/locales/en/translation.json, fe/src/utils/locales/ku/translation.json, fe/src/utils/locales/tr/translation.json
improved for better space usage
=> useful articles -> tabular

data/parsers/yemek.py, pdfConverterAPI/leafGenerator/data.json
google sahra mutfak haritasi 
https://www.google.com/maps/d/viewer?mid=1LspPt4CpxG6krYf2ABBZISBbqd4SZs0&g_ep=CAISBjYuNTEuNhgAIN1iQgJUUg%3D%3D&g_st=ic&ll=37.14265800412934%2C37.21008814999998&z=9
=> add Earthquake Zone Sahara Kitchen Map

maps/src/Map.css, maps/src/Map.tsx
=> Maps - Bigger checkboxes for filtering on mobile, colorful markers

README.MD
Proje sayfasından tıklandığında GitHub içinde alt sayfaya olarak yorumluyor ve 404 hatası veriyordu.
=> Bağlatı referansı onarıldı.

maps/src/CustomMarker.tsx, maps/src/Map.tsx
=> Maps - Populate marker popup with data

maps/src/hooks.ts
=> change angle for on top maps, fix #133

.github/workflows/pdf-generate-upload-markdown.yaml, fe/src/utils/downloadPDF.ts
=> Feat: Purge Cloudflare cache after PDF generation

data/combine.py, fe/src/components/data/GasStationsData.tsx, maps/src/Map.tsx
- This pr adds missing kurdish title while removing forgotten logs
=> Add missing kurdish data

fe/src/components/Question.tsx
- This pr fixes the scrolling issue on page change where cursor stay at the same position with the last page
=> Fix scroll issue

fe/src/components/data/TransportationsData.tsx
Resolves #163 
Localizationdaki t için type ekledim aslında ama excessive deep diyor error throwluyor, geri aldım.
=> validity date null check

fe/src/components/Question.tsx, fe/src/components/data/BankData.tsx, fe/src/components/data/ContainerPharmacyData.tsx, fe/src/components/data/EvacuationData.tsx, fe/src/components/data/GasStationsData.tsx
Some of the listitem key props were missing.
They will all be completed with the pr #163
=> FE - fix missing ListItem keys.

fe/src/App.tsx, fe/src/components/PDFDownloadDialog.tsx, fe/src/declerations.d.ts, fe/src/utils/locales/ar/translation.json, fe/src/utils/locales/en/translation.json, fe/src/utils/locales/il_translate.json, fe/src/utils/locales/ku/translation.json, fe/src/utils/locales/tr/translation.json
Translations will be added later. DO NOT MERGE
=> PDF Download Dialog

maps/package.json, maps/src/Map.css, maps/src/Map.tsx, maps/yarn.lock
Eğer sadece konum izni varsa çalışan bir buton ekledim. Tıklandığında harita görünümnü mavi CircleMarker'a yani kullanıcının konumuna ayarlıyor. Eğer kullanıcı konum izni vermemişse buton da gözükmüyor.
Butonun tasarımı değiştirilebilir.
=> Add setView to self location button

.github/workflows/cron-data-upload.yaml, .github/workflows/map-data-upload.yaml, .github/workflows/pdf-generate-upload-markdown.yaml, pdf-markdown/generate.sh
Fixes https://github.com/alpaylan/afetbilgi.com/issues/198
=> Feat: Use new backup bucket with lifecycle policy for generated file backups

fe/src/components/Data.tsx, fe/src/hooks.ts
Örnek: /Güvenli%20Toplanma%20Alanları/Adana
=> Son 24 saat içinde güncellenmiştir etiketi
